---
language: node_js
node_js:
  - "8.1.0"

sudo: false

cache:
  yarn: true

env:
  - PACKAGE_NAME=contracts-lib
  - PACKAGE_NAME=custom-contracts

before_install:
  - npm install --global yarn@0.27.5
  - yarn setup
  - cd ./packages/$PACKAGE_NAME

install:
  - yarn install --pure-lockfile

script:
  - yarn test
